useCustomEconomy: true

message:
  no-permission: "&c&lERROR! &cYou do not have permission to use this command!"
  invalid-arguments: "&c&lERROR! &cInvalid arguments!"
  invalid-player: "&c&lERROR! &cInvalid player!"
  invalid-number: "&c&lERROR! &cInvalid number!"
  no-account: "&c&lERROR! &cPlayer doesn't have account!"
  not-enough-money: "&c&lERROR! &cYou do not have enough money!"
  balance-me: "&aYour balance is: &e$%balance%!"
  balance-other: "&a%player%'s balance is: &e$%balance%!"

earning:
  #Only triggers if user has a pickaxe
  mining:
    STONE: 1
    COAL_ORE: 0.05
    IRON_ORE: 0.1

  #Only triggers if user has a hoe or empty hand
  farming:
    WHEAT: 0.01
    CARROT: 0.01
    POTATO: 0.01
    BEETROOT: 0.01
    MELON: 0.01
    PUMPKIN: 0.01
    COCOA_BEANS: 0.01
    NETHER_WART: 0.01

  #Only triggers if user has a fishing rod
  fishing:
    COD: 0.01
    SALMON: 0.01

  mobs:
    ZOMBIE: 0.01
    SKELETON: 0.01
    CREEPER: 0.01

  #Only triggers if user has an axe,pickaxe or empty hand
  woodcutting:
    OAK_LOG: 0.01
    SPRUCE_LOG: 0.01
    BIRCH_LOG: 0.01
    SUGAR_CANE: 0.1
    #Sugar cane is a special case, since it's not a crop, but a block it has to be added here

  crafting:
    DIAMOND_SWORD: 10
    DIAMOND_PICKAXE: 20
    DIAMOND_AXE: 25