name: SurvivalAIO
version: '1.1'
main: me.anon695.survivalaio.SurvivalAIO
api-version: '1.18'
depend:
  - Vault
commands:
  economy:
    aliases:
      - eco
      - econ
  balance:
    aliases:
      - bal
  earning:
    aliases:
      - earn
  pay:
    aliases:
      - send